# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=0.1.0-alpha.12

maven_group=pers.solid.ecmd

archives_base_name=enhanced_commands

enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.4
parchment_version=2025.03.23

# Dependencies

## check Fabric version https://fabricmc.net/develop/
fabric_loader_version=0.19.1
fabric_api_version=0.119.4+1.21.4

## check NeoForge version https://neoforged.net/
neoforge_version=21.4.157

## check Mod Menu (Fabric) version https://modrinth.com/mod/modmenu/versions?g=1.21.4
modmenu_version=13.0.4

## check IMBlocker version https://modrinth.com/mod/imblocker-original/versions?g=1.21.4
imblocker_fabric_version=VlojK7Ty
imblocker_neoforge_version=FGYhLbmY

## check Better Selection version https://modrinth.com/mod/better-selection/versions?g=1.21.4
better_selection_version=1.6.8

# Downloading sources
#loom_libraries_base=https://bmclapi2.bangbang93.com/maven/
loom_resources_base=https://bmclapi2.bangbang93.com/assets/
loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json
loom_fabric_repository=https://repository.hanbings.io/proxy/